# export DB=[h2|mysql]
# mvn -P $DB -pl application clean package
# docker build -f Dockerfile-newrelic -t texastoc-v4-$DB-newrelic-image .
FROM openjdk:17-alpine
EXPOSE 8080
COPY server/target/texastoc-server-v5-1.0.0.jar /server/
ADD third-party/newrelic-java /server/
ENTRYPOINT ["java"]
CMD [ \
    "-javaagent:/server/newrelic/newrelic.jar", \
    "-jar", \
    "/server/texastoc-server-v5-1.0.0.jar" \
]
